apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  labels:
    app: integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
      - name: integration-service
        image: simondum/integration-service:1.0
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_DB
          value: insa
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "admin"